# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10vG_BSuDyR_Lw22CLjppCjHfEr_Tt661
"""

import numpy as np

# 1.Massiv yaratish
array_1d = np.array([1,2,3,4,5])